apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db-nfs
    spec:
      containers:
      - name: db-nfs
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "0000"  
          - name: MYSQL_DATABASE
            value: "db"
          - name: MYSQL_USER
            value: "magento"
          - name: MYSQL_PASSWORD
            value: "0000"
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: db-nfs-pvc
            mountPath: "/var/lib/mysql"
        resources:
          requests:
            memory: "500Mi"
            cpu: "550m"
          limits:
            memory: "600Mi"
            cpu: "600m"
      volumes:
      - name: db-nfs-pvc
        persistentVolumeClaim:
          claimName: db-nfs-pvc