apiVersion: v1
kind: PersistentVolume
metadata:
 name: db-nfs-pv
spec:
 accessModes:
   - ReadWriteMany
 capacity:
   storage: 10Gi
 nfs:
   server: 192.168.64.61
   path: "/mnt/nfs/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: db-nfs-pvc
spec:
 accessModes:
 - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 volumeName: "db-nfs-pv"