apiVersion: v1
kind: PersistentVolume
metadata:
 name: www-nfs-pv
spec:
 accessModes:
   - ReadWriteMany
 capacity:
   storage: 10Gi
 nfs:
   server: 192.168.64.61
   path: "/mnt/nfs/www"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: www-nfs-pvc
spec:
 accessModes:
 - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 volumeName: "www-nfs-pv"





# apiVersion: v1
# kind: PersistentVolume
# metadata:
#  name: siud-webadm-uploads
# spec:
#  accessModes:
#    - ReadWriteMany
#  capacity:
#    storage: 10Gi
#  nfs:
#    server: 10.0.0.16
#    path: "/shares/share-51831cd4-2fe9-4f08-ac45-6be754556519"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#  name: siud-webadm-upload
# spec:
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 10Gi
#  volumeName: "siud-webadm-uploads"
# mount -t nfs  192.18.64.61:/mnt/nfs/www   ~/nfs/